# Generated by Django 3.0.7 on 2021-10-05 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211005_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 14, 44, 45, 639613)),
        ),
    ]
